name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download Depencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get -y install build-essential libc6-dev-i386 \
        linux-libc-dev:i386 gcc-arm-none-eabi libnewlib-arm-none-eabi \
        gcc-*-multilib gcc-*-aarch64-linux-gnu gcc-*-powerpc-linux-gnu \
        gcc-aarch64-linux-gnu gcc-powerpc-linux-gnu libc6-arm64-cross \
        libc6-powerpc-cross libc6-dev-arm64-cross libc6-dev-powerpc-cross \
        qemu lcov qemu-user-binfmt

    - name: run build script
      run: |
        scripts/build.sh
        (pushd player/; ./build.sh linux; popd)

    - name: after build sctips
      run: bash <(curl -s https://codecov.io/bash)

